name: ci

on:
  push:
    branches:
      - 'main'

using-an-action
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and push Docker image
        with:
          context: image/
          push: true
          tags: ghcr.io/1n73llx/apk-builder:latest
