name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry

uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.PAT }}

- name: Build the Docker image

run: |
       docker build . --tag ghcr.io/1n73llx/apk-builder:latest
       docker run ghcr.io/1n73llx/apk-builder:latest
       docker push ghcr.io/1n73llx/apk-builder:latest
