name: Build and Push Docker Image

on:
  push:
    branches:
      - main
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GHCR
      env:
        CR_PAT: ${{ secrets.PAT }}
        run: echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Docker image
      env:
        IMAGE_NAME: apk-builder
      run: |
          docker build . -t ghcr.io/${{ github.actor }}/$IMAGE_NAME:latest
          docker push ghcr.io/${{ github.actor }}/$IMAGE_NAME:latest
